language: python
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-lxml python-pip
install:
- deactivate
- gem install kramdown-rfc2629
- sudo pip install xml2rfc
script: make ghpages
env:
  global:
  - secure: QWDQua2thAf5ZXhUjk1z0Px888+spfI7OrGA/Ty99B3XQN1Gm7ax7lNWftO5WT3nEEVPlA/rRgP9ZGSXrM7BMbKB0DlZjgwIey3gt8vlE+qUvqzULFPbFF1e5knPwL6IO1LtgzO5J8CUmhUCzGbPU0t9nbcO67ZeqimmZ5qeYiA=
